# ----------------------------------------------------------------------------------------------------------------------
# Eureka配置
# ----------------------------------------------------------------------------------------------------------------------
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: "http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/"
  instance:
    instance-id: "${spring.application.name}:${random.value}"
    prefer-ip-address: true
    hostname: "${HOSTNAME}"
