# ----------------------------------------------------------------------------------------------------------------------
# FeignClient超时配置
# ----------------------------------------------------------------------------------------------------------------------
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000

feign:
  client:
    config:
      default:
        connectTimeout: 6000
        readTimeout: 6000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 1000
