version: "3.5"

services:

  eureka:
    image: "sce/node-eureka:1.0.0"
    container_name: "sce-eureka"
    ports:
      - 8761:8761
    volumes:
      - ${PWD}/log/eureka/:/log/

  api-gateway:
    image: "sce/node-apigateway:1.0.0"
    container_name: "sce-apigateway"
    ports:
      - 5555:5555
    links:
      - eureka:eureka
