# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
spring:
  datasource:
    driver-class-name: "org.mariadb.jdbc.Driver"
    url: "jdbc:mariadb://10.211.55.26:3310/demo?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8"
    username: "root"
    password: "root"
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: "org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy"
    database-platform: "org.hibernate.dialect.MySQL5InnoDBDialect"
    properties:
        hibernate:
          format_sql: true
          enable_lazy_load_no_trans: false
  redis:
    database: 0
    host: "10.211.55.26"
    port: "6379"
    password: "133810"

# ----------------------------------------------------------------------------------------------------------------------
# Eureka配置
# ----------------------------------------------------------------------------------------------------------------------
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
  instance:
    instance-id: "${spring.application.name}:${random.value}"
    hostname: "127.0.0.1"
