# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
spring:
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/demo?useSSL=true&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8"
    username: "root"
    password: "root"
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: "org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy"
    database-platform: "org.hibernate.dialect.MySQL5InnoDBDialect"
    properties:
        hibernate:
          format_sql: false
          enable_lazy_load_no_trans: false
          dialect:
            storage_engine: innodb

# ----------------------------------------------------------------------------------------------------------------------
# Eureka配置
# ----------------------------------------------------------------------------------------------------------------------
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: "http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/"
  instance:
    instance-id: "${spring.application.name}:${random.value}"
    prefer-ip-address: true
    hostname: "${HOSTNAME}"
