version: "3.5"

services:

  # -------------------------------------------------
  # 服务治理
  # -------------------------------------------------

  eureka:
    image: "sce/node-eureka"
    container_name: "sce-eureka"
    ports:
    - 8761:8761
    volumes:
    - ${PWD}/log/:/log/
    env_file:
    - ${PWD}/env.sh

  # -------------------------------------------------
  # 集中配置
  # -------------------------------------------------

  configuration:
    image: "sce/node-configuration"
    container_name: "sce-configuration"
    ports:
    - 9990:9990
    links:
    - eureka:eureka
    volumes:
    - ${PWD}/log/:/log/
    - ~/.ssh/:/root/.ssh/:ro
    env_file:
    - ${PWD}/env.sh

  # -------------------------------------------------
  # 服务网关
  # -------------------------------------------------

  api-gateway:
    image: "sce/node-apigateway"
    container_name: "sce-apigateway"
    links:
    - eureka:eureka
    ports:
    - 5555:5555
    volumes:
    - ${PWD}/log/:/log/
    env_file:
    - ${PWD}/env.sh

  # -------------------------------------------------
  # 服务生产者
  # -------------------------------------------------

  service-provider:
    image: "sce/node-service-provider"
    container_name: "sce-provider"
    links:
    - eureka:eureka
    ports:
    - 8080:8080
    volumes:
    - ${PWD}/log/:/log/
    env_file:
    - ${PWD}/env.sh

  # -------------------------------------------------
  # 服务消费者
  # -------------------------------------------------

  service-consumer:
    image: "sce/node-service-consumer"
    container_name: "sce-consumer"
    links:
    - eureka:eureka
    ports:
    - 7080:7080
    volumes:
    - ${PWD}/log/:/log/
    env_file:
    - ${PWD}/env.sh

networks:
  default:
    external:
      name: tiger
