version: "3.5"

services:

  # -------------------------------------------------
  # 服务治理
  # -------------------------------------------------

  eureka:
    image: "sce/node-eureka:1.0.0"
    container_name: "sce-eureka"
    ports:
      - 8761:8761
    volumes:
      - ${PWD}/log/eureka/:/log/
    env_file:
      - ${PWD}/env.sh

  # -------------------------------------------------
  # 服务网关
  # -------------------------------------------------

  api-gateway:
    image: "sce/node-apigateway:1.0.0"
    container_name: "sce-apigateway"
    links:
      - eureka:eureka
    ports:
      - 5555:5555
    volumes:
      - ${PWD}/log/api-gatway/:/log/
    env_file:
      - ${PWD}/env.sh

  # -------------------------------------------------
  # 服务生产者
  # -------------------------------------------------

  service-provider:
    image: "sce/node-service-provider:1.0.0"
    container_name: "sce-provider"
    links:
      - eureka:eureka
    ports:
      - 8080:8080
    extra_hosts:
      - "outside:172.17.0.1"
    volumes:
      - ${PWD}/log/service-provider/:/log/
    env_file:
      - ${PWD}/env.sh

  # -------------------------------------------------
  # 服务消费者
  # -------------------------------------------------

  service-consumer:
    image: "sce/node-service-consumer:1.0.0"
    container_name: "sce-consumer"
    links:
      - eureka:eureka
    ports:
      - 7080:7080
    volumes:
      - ${PWD}/log/service-consumer/:/log/
    env_file:
      - ${PWD}/env.sh

networks:
   default:
     external:
       name: mirai
